name: Label Check

on:
  pull_request:
    branches:
      - master

jobs:
  label-check:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello
        run: echo Hello World !
      - name: Check out repositort
        run: |
          Author : ${{ github.actor }}
          Workspace: ${{ github.workspace }}





